// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain.proto

package blockchainpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddBlockRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBlockRequest) Reset()         { *m = AddBlockRequest{} }
func (m *AddBlockRequest) String() string { return proto.CompactTextString(m) }
func (*AddBlockRequest) ProtoMessage()    {}
func (*AddBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{0}
}

func (m *AddBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBlockRequest.Unmarshal(m, b)
}
func (m *AddBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBlockRequest.Marshal(b, m, deterministic)
}
func (m *AddBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBlockRequest.Merge(m, src)
}
func (m *AddBlockRequest) XXX_Size() int {
	return xxx_messageInfo_AddBlockRequest.Size(m)
}
func (m *AddBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBlockRequest proto.InternalMessageInfo

func (m *AddBlockRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AddBlockResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBlockResponse) Reset()         { *m = AddBlockResponse{} }
func (m *AddBlockResponse) String() string { return proto.CompactTextString(m) }
func (*AddBlockResponse) ProtoMessage()    {}
func (*AddBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{1}
}

func (m *AddBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBlockResponse.Unmarshal(m, b)
}
func (m *AddBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBlockResponse.Marshal(b, m, deterministic)
}
func (m *AddBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBlockResponse.Merge(m, src)
}
func (m *AddBlockResponse) XXX_Size() int {
	return xxx_messageInfo_AddBlockResponse.Size(m)
}
func (m *AddBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBlockResponse proto.InternalMessageInfo

func (m *AddBlockResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetBlockchainRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockchainRequest) Reset()         { *m = GetBlockchainRequest{} }
func (m *GetBlockchainRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockchainRequest) ProtoMessage()    {}
func (*GetBlockchainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{2}
}

func (m *GetBlockchainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockchainRequest.Unmarshal(m, b)
}
func (m *GetBlockchainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockchainRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockchainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockchainRequest.Merge(m, src)
}
func (m *GetBlockchainRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockchainRequest.Size(m)
}
func (m *GetBlockchainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockchainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockchainRequest proto.InternalMessageInfo

type Block struct {
	Index                int64                `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash                 string               `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	PrevBlockHash        string               `protobuf:"bytes,4,opt,name=prevBlockHash,proto3" json:"prevBlockHash,omitempty"`
	Data                 string               `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *Block) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetBlockchainResponse struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockchainResponse) Reset()         { *m = GetBlockchainResponse{} }
func (m *GetBlockchainResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockchainResponse) ProtoMessage()    {}
func (*GetBlockchainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{4}
}

func (m *GetBlockchainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockchainResponse.Unmarshal(m, b)
}
func (m *GetBlockchainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockchainResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockchainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockchainResponse.Merge(m, src)
}
func (m *GetBlockchainResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockchainResponse.Size(m)
}
func (m *GetBlockchainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockchainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockchainResponse proto.InternalMessageInfo

func (m *GetBlockchainResponse) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*AddBlockRequest)(nil), "protos.AddBlockRequest")
	proto.RegisterType((*AddBlockResponse)(nil), "protos.AddBlockResponse")
	proto.RegisterType((*GetBlockchainRequest)(nil), "protos.GetBlockchainRequest")
	proto.RegisterType((*Block)(nil), "protos.Block")
	proto.RegisterType((*GetBlockchainResponse)(nil), "protos.GetBlockchainResponse")
}

func init() { proto.RegisterFile("blockchain.proto", fileDescriptor_e9ac6287ce250c9a) }

var fileDescriptor_e9ac6287ce250c9a = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x5d, 0x29, 0x8d, 0x9d, 0x8a, 0x36, 0x93, 0xaa, 0x84, 0x68, 0x24, 0xc4, 0x1a, 0x4e,
	0x34, 0xc1, 0x8b, 0x27, 0x8d, 0x5c, 0xf4, 0xe4, 0x81, 0x78, 0xf2, 0x06, 0x65, 0x2d, 0xc4, 0x96,
	0xc5, 0xee, 0xd6, 0xf8, 0x65, 0x3c, 0xfa, 0x3d, 0x0d, 0xbb, 0x2c, 0xd8, 0xaa, 0xa7, 0xfd, 0xf3,
	0xde, 0xec, 0xfe, 0xe6, 0x65, 0x60, 0x94, 0x2e, 0xd8, 0xec, 0x75, 0x96, 0x27, 0x45, 0x19, 0x54,
	0x2b, 0x26, 0x18, 0xf6, 0xe5, 0xc2, 0x9d, 0xf3, 0x39, 0x63, 0xf3, 0x05, 0x9d, 0xca, 0x63, 0xba,
	0x7e, 0x99, 0x8a, 0x62, 0x49, 0xb9, 0x48, 0x96, 0x95, 0x32, 0x7a, 0x13, 0x38, 0xbc, 0xcb, 0xb2,
	0xa8, 0xae, 0x8f, 0xe9, 0xdb, 0x9a, 0x72, 0x81, 0x08, 0xbd, 0x2c, 0x11, 0x89, 0x4d, 0x5c, 0xe2,
	0x0f, 0x62, 0xb9, 0xf7, 0x2e, 0x61, 0xd4, 0xd9, 0x78, 0xc5, 0x4a, 0x4e, 0x6b, 0x5f, 0x9e, 0xf0,
	0x5c, 0xfb, 0xea, 0xbd, 0x77, 0x0c, 0xe3, 0x7b, 0x2a, 0xa2, 0x16, 0xa7, 0x79, 0xd3, 0xfb, 0x22,
	0x60, 0xca, 0x5b, 0x1c, 0x83, 0x59, 0x94, 0x19, 0xfd, 0x90, 0x65, 0x46, 0xac, 0x0e, 0x78, 0x0d,
	0x83, 0x96, 0xcc, 0xde, 0x75, 0x89, 0x3f, 0x0c, 0x9d, 0x40, 0xb1, 0x07, 0x9a, 0x3d, 0x78, 0xd2,
	0x8e, 0xb8, 0x33, 0xb7, 0x14, 0x46, 0x47, 0x81, 0x17, 0x60, 0x55, 0x2b, 0xfa, 0x2e, 0x3f, 0x7c,
	0xa8, 0xc5, 0x9e, 0x14, 0x37, 0x2f, 0xdb, 0x3e, 0xcd, 0x1f, 0x7d, 0xde, 0xc0, 0xd1, 0x16, 0x7f,
	0xd3, 0xec, 0x04, 0xfa, 0x32, 0x64, 0x6e, 0x13, 0xd7, 0xf0, 0x87, 0xa1, 0xa5, 0xb0, 0x78, 0xa0,
	0x32, 0x69, 0xc4, 0xf0, 0x93, 0x00, 0x74, 0xd5, 0x78, 0x0b, 0x7b, 0x3a, 0x36, 0x3c, 0xd1, 0x15,
	0x5b, 0x79, 0x3b, 0xf6, 0x6f, 0x41, 0x7d, 0xea, 0xed, 0xe0, 0x23, 0x58, 0x1b, 0x3c, 0x78, 0xaa,
	0xcd, 0x7f, 0xc5, 0xec, 0x9c, 0xfd, 0xa3, 0xea, 0xf7, 0xa2, 0x83, 0xe7, 0xfd, 0x6e, 0x56, 0xaa,
	0x34, 0x55, 0x73, 0x72, 0xf5, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xd4, 0xf6, 0x5b, 0x42, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainClient is the client API for Blockchain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainClient interface {
	AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*AddBlockResponse, error)
	GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error)
}

type blockchainClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainClient(cc *grpc.ClientConn) BlockchainClient {
	return &blockchainClient{cc}
}

func (c *blockchainClient) AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*AddBlockResponse, error) {
	out := new(AddBlockResponse)
	err := c.cc.Invoke(ctx, "/protos.Blockchain/AddBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error) {
	out := new(GetBlockchainResponse)
	err := c.cc.Invoke(ctx, "/protos.Blockchain/GetBlockchain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainServer is the server API for Blockchain service.
type BlockchainServer interface {
	AddBlock(context.Context, *AddBlockRequest) (*AddBlockResponse, error)
	GetBlockchain(context.Context, *GetBlockchainRequest) (*GetBlockchainResponse, error)
}

func RegisterBlockchainServer(s *grpc.Server, srv BlockchainServer) {
	s.RegisterService(&_Blockchain_serviceDesc, srv)
}

func _Blockchain_AddBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).AddBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Blockchain/AddBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).AddBlock(ctx, req.(*AddBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_GetBlockchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockchainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetBlockchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Blockchain/GetBlockchain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetBlockchain(ctx, req.(*GetBlockchainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blockchain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Blockchain",
	HandlerType: (*BlockchainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBlock",
			Handler:    _Blockchain_AddBlock_Handler,
		},
		{
			MethodName: "GetBlockchain",
			Handler:    _Blockchain_GetBlockchain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain.proto",
}
